### ISSUE TITLE
Network Error in plugin

### ISSUE THREAD

**Issue by andypiper** [mhawkshaw/homebridge-enviroplus#1]
**Describe The Bug:**

In the past few days - I’m not certain exactly when this started, or whether a node or other upgrade was involved - the plugin has started to return a network error.

The frustrating part is that I’m able to access http://zero-enviro.local:8001/ and get the JSON output from a browser running on a different machine; and also run `curl http://zero-enviro.local:8001/` at the console on the homebridge server:

```
pi@homebridge:~ $ curl http://zero-enviro.local:8001
{"temperature": "21.55", "pressure": "100301.49", "humidity": "40.35", "P2": "2", "P1": "4"}pi@homebridge:~
```

**Logs:**

```
[25/12/2021, 16:35:17] [EnviroplusAirQuality] Unable to obtain data from Enviro+ Server http://zero-enviro.local:8001 Error: Network Error
    at XMLHttpRequest.req.onerror (/usr/local/lib/node_modules/homebridge-enviroplus/src/platformAccessory.ts:43:16)
    at XMLHttpRequest.dispatchEvent (/usr/local/lib/node_modules/homebridge-enviroplus/node_modules/src/XMLHttpRequest.ts:803:49)
    at XMLHttpRequest.handleError (/usr/local/lib/node_modules/homebridge-enviroplus/node_modules/src/XMLHttpRequest.ts:866:14)
    at ClientRequest.errorHandler_1 (/usr/local/lib/node_modules/homebridge-enviroplus/node_modules/src/XMLHttpRequest.ts:553:22)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Plugin Config:**

This is the Enviro+ section of the homebridge config.

```json
       {
            "server": "http://zero-enviro.local:8001",
            "serial": "1234567890",
            "interval": 5,
            "excellent": 10,
            "good": 20,
            "fair": 25,
            "inferior": 50,
            "poor": 50,
            "platform": "EnviroplusAirQuality"
        }
```

**Environment:**

* **Plugin Version**: 1.0.2
* **Homebridge Version**: 1.3.8
* **Node.js Version**: 16.13.1
* **NPM Version**: 8.1.2
* **Operating System**: Raspberry Pi OS Bullseye

**Comment by andypiper** [comment]
Doing some debugging on this locally. I modified platformAccessory.js to log the error in more detail, and it looks like it is hitting a DNS error:

```
Error: getaddrinfo ENOTFOUND zero-enviro.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
```

Still digging around here, but this may be an IPv6 thing. I’ve also had some situations where the homebridge box has showed up with incremental suffixes in Avahi, so I’ll have to see if there’s something going wrong in the network configuration.

**Comment by andypiper** [comment]
Current status is that I’ve disabled ipv6 usage in `/etc/avahi/avahi-daemon.conf` and also edited `/etc/nsswitch.conf` to prioritise mdns over dns. This appears to have resolved the issue locally (more likely to be the former edit than the latter, I think). One of these days I need to do a proper network remap at home to sort out all of these lookup and naming oddities…

**Comment by mhawkshaw** [comment]
Thanks for investigating. I have both IPv4 and IPv6 on my network, and haven't experienced these problems with this plug-in. It shouldn't be necessary to disable IPv6. If after you've had a look at your network and you still have problems, let me know.
