### ISSUE TITLE
Air Quality failed to display and shows warning characteristics

### ISSUE THREAD

**Issue by mikenhu** [mhawkshaw/homebridge-enviroplus#9]
**Describe The Bug:**
The plugin returns undefined value for Air Quality in HomeKit.

**To Reproduce:**
This is from a fresh installation. After installing the plugin and configuring it to work with MQTT accordingly, all sensors responded well, but air quality failed to display.

**Expected behavior:**
The air quality should return a range of fair/good/excellent value as defined in the configuration.

**Logs:**

```
[18/09/2022, 21:04:59] [EnviroplusAirQuality] Connected to MQTT broker
[18/09/2022, 21:04:59] [EnviroplusAirQuality] enviro was subscribed
[18/09/2022, 21:04:59] [EnviroplusAirQuality] {"temperature": 13, "pressure": 99750, "humidity": 50, "oxidised": 1, "reduced": 422, "nh3": 21, "lux": 0, "serial": "xxxxxxx"}
[18/09/2022, 21:05:00] [EnviroplusAirQuality] Air Quality -> 0
[18/09/2022, 21:05:00] [EnviroplusAirQuality] PM10 Density -> undefined
[18/09/2022, 21:05:00] [EnviroplusAirQuality] PM2.5 Density -> undefined
[18/09/2022, 21:05:00] [EnviroplusAirQuality] Temperature -> 13
[18/09/2022, 21:05:00] [EnviroplusAirQuality] Humidity -> 50
[18/09/2022, 21:05:00] [EnviroplusAirQuality] Light -> 0.0001
[18/09/2022, 21:05:00] [homebridge-enviroplus] This plugin generated a warning from the characteristic 'PM10 Density': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[18/09/2022, 21:05:00] [homebridge-enviroplus] Error: 
    at PM10Density.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at PM10Density.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2030:14)
    at PM10Density.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1534:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[18/09/2022, 21:05:00] [homebridge-enviroplus] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[18/09/2022, 21:05:00] [homebridge-enviroplus] Error: 
    at PM2_5Density.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at PM2_5Density.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2030:14)
    at PM2_5Density.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1534:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Plugin Config:**

```json
        {
            "mqttbroker": "mqtt://192.168.0.28:1883",
            "topic": "enviro",
            "username": "xxx",
            "password": "xxx",
            "serial": "xxx",
            "excellent": 10,
            "good": 20,
            "fair": 25,
            "inferior": 50,
            "poor": 50,
            "platform": "EnviroplusAirQuality"
        }
```

**Screenshots:**
<img width="1485" alt="Screen Shot 2022-09-18 at 21 10 22" src="https://user-images.githubusercontent.com/9059129/190922096-f25d5f9a-4ac1-4144-88e7-d578a6a2b5c4.png">

![IMG_D2579DCB7598-1](https://user-images.githubusercontent.com/9059129/190922272-97ef90db-21a5-4e56-a0f1-a8f55f94b7b5.jpeg)

**Environment:**

* **Plugin Version**: 2.0.3
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.17.0
* **NPM Version**: 8.15.0
* **Operating System**: Raspbian GNU/Linux 11 (bulleye)

**Comment by mhawkshaw** [comment]
Hi @mikenhu,

Can you tell me what Pimoroni device you have? Looking at the JSON data being sent over MQTT to the Homebridge plug-in, you're missing the following entries: "pm1" and "pm25" so the data for air quality is not being sent.

**Comment by mikenhu** [comment]
Hi. It is the Enviro + Air Quality and I configured the device following the homebridge plugin UI itself.

**Comment by mhawkshaw** [comment]
Which script from [this repository](https://github.com/pimoroni/enviroplus-python/tree/master/examples) are you running to send the data to the Homebridge plug-in? This one? [mqtt-all.py](https://github.com/pimoroni/enviroplus-python/blob/master/examples/mqtt-all.py)

The Homebridge plug-in is expecting JSON data like this:

{"temperature": 24, "pressure": 99080, "humidity": 47, "oxidised": 33, "reduced": 1024, "nh3": 1810, "lux": 0, "pm1": 6, "pm25": 7, "pm10": 7, "serial": "0000000012345def"}

The script you are running is sending this:

{"temperature": 13, "pressure": 99750, "humidity": 50, "oxidised": 1, "reduced": 422, "nh3": 21, "lux": 0, "serial": "xxxxxxx"}

As you can see, the entries "pm1", "pm25" and "pm10" are missing. This means either there's a problem with your external air quality sensor, or you're running a different script that isn't sending these values.

**Comment by mikenhu** [comment]
I used the mqtt-all.py alright. Tested with the script as well. I just don't know why it does not show up. Anyway I supposed it is not the issue of the plug-in like you said. I'll close the ticket now. Sorry for the inconvenience!

**Comment by mhawkshaw** [comment]
If you have the [Enviro for Raspberry Pi](https://shop.pimoroni.com/products/enviro?variant=31155658457171) then you also need to have the [particulate matter sensor](https://shop.pimoroni.com/products/pms5003-particulate-matter-sensor-with-cable?variant=29075640352851) attached to get the particulate matter data (PM1, PM2.5, PM10). The mqtt-all.py tries to connect to this and if it can't then the JSON data isn't sent. From the command line you'll see the message "No PMS5003 sensor connected".
